VENDOR_LENGTH = 30
MODEL_NUMBER_LENGTH = 40
SERIAL_NUMBER_LENGTH = 40
DESCRIPTION_LENGTH = 100
COMMENT_LENGTH = 2000
CALIBRATION_FREQUENCY_LENGTH = 10  # needs to be validated in manager, length not valid for integer field
CATEGORY_LENGTH = 40
