# Generated by Django 3.1.5 on 2021-01-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.TextField(default=None)),
                ('model_number', models.TextField(default=None)),
                ('description', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('calibration_frequency', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default=None)),
                ('name', models.TextField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.TextField(default=None)),
                ('admin', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.TextField(default=None)),
                ('comment', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.model')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('comment', models.TextField(blank=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
