# Generated by Django 3.1.5 on 2021-01-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalibrationHistory',
            new_name='CalibrationEvent',
        ),
    ]
