# Generated by Django 3.1.5 on 2021-02-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('model', 'serial_number')},
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('vendor', 'model_number')},
        ),
    ]
