# Generated by Django 3.1.5 on 2021-02-08 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210208_0149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='EquipmentModel',
        ),
    ]
