# Generated by Django 3.1.5 on 2021-01-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210128_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
