# Generated by Django 3.1.6 on 2021-02-10 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210209_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationevent',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='calibrationevent',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_history', to='database.instrument'),
        ),
    ]
