# Generated by Django 3.1.5 on 2021-02-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210208_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='model_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='vendor',
            field=models.TextField(),
        ),
    ]
