# Generated by Django 3.1.5 on 2021-02-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210209_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calibrationevent',
            options={'ordering': ['date']},
        ),
    ]
