# Generated by Django 3.1.5 on 2021-02-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210131_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=None),
        ),
    ]
