# Generated by Django 3.1.5 on 2021-02-09 19:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210209_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2021, 2, 9))]),
        ),
    ]
