# Generated by Django 3.1.5 on 2021-02-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationevent',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationevent',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='model',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_number',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
