# Generated by Django 3.1.5 on 2021-02-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210205_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='vendor',
            field=models.CharField(default=None, max_length=1),
        ),
    ]
