# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install Django
        python -m pip install openpyxl
        python -m pip install djangorestframework
        python -m pip install markdown
        python -m pip install django-filter
        python -m pip install djoser
    - name: Make migrations
      run: python manage.py makemigrations
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
    - name: Django Security Check
      # You may pin to the exact commit or the version.
      # uses: victoriadrake/django-security-check@762dd0ab80194dbded70117daa32bd7d139c6a04
      uses: victoriadrake/django-security-check@v1.1.0
